# Generated by Django 4.0.3 on 2022-03-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='date_submitted',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='email',
        ),
    ]
