# Generated by Django 4.0.3 on 2022-03-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_subscribe_date_submitted_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
